### ISSUE TITLE
[Wish] Indigo Clear Variations

### ISSUE THREAD

**Issue by fuzenco** [p3rception/Indigo-zed#1]
The Indigo Clear theme is amazing with its translucency. Thank you. Would it be possible to get alternate colors of that theme?

**Comment by p3rception** [comment]
Hey @fuzenco, sorry for the late response. Glad you like the theme! Currently I'm not planning any color variations but you never know. Feel free to check the fork from @acquitelol [1]. 

[1] https://github.com/acquitelol/zed-themes
